/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.venkat.scala.entity;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** The key which uniquely identifies EmployeeKey */
@org.apache.avro.specific.AvroGenerated
public class EmployeeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8593954775962161298L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeKey\",\"namespace\":\"com.venkat.scala.entity\",\"doc\":\"The key which uniquely identifies EmployeeKey\",\"fields\":[{\"name\":\"empId\",\"type\":\"string\",\"doc\":\"Source which uniquely identifies employee Id\"}],\"globalId\":\"123\",\"root\":\"true\",\"version\":\"0\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Source which uniquely identifies employee Id */
  @Deprecated public java.lang.CharSequence empId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeKey() {}

  /**
   * All-args constructor.
   * @param empId Source which uniquely identifies employee Id
   */
  public EmployeeKey(java.lang.CharSequence empId) {
    this.empId = empId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return empId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: empId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'empId' field.
   * @return Source which uniquely identifies employee Id
   */
  public java.lang.CharSequence getEmpId() {
    return empId;
  }

  /**
   * Sets the value of the 'empId' field.
   * Source which uniquely identifies employee Id
   * @param value the value to set.
   */
  public void setEmpId(java.lang.CharSequence value) {
    this.empId = value;
  }

  /**
   * Creates a new EmployeeKey RecordBuilder.
   * @return A new EmployeeKey RecordBuilder
   */
  public static com.venkat.scala.entity.EmployeeKey.Builder newBuilder() {
    return new com.venkat.scala.entity.EmployeeKey.Builder();
  }

  /**
   * Creates a new EmployeeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeKey RecordBuilder
   */
  public static com.venkat.scala.entity.EmployeeKey.Builder newBuilder(com.venkat.scala.entity.EmployeeKey.Builder other) {
    return new com.venkat.scala.entity.EmployeeKey.Builder(other);
  }

  /**
   * Creates a new EmployeeKey RecordBuilder by copying an existing EmployeeKey instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeKey RecordBuilder
   */
  public static com.venkat.scala.entity.EmployeeKey.Builder newBuilder(com.venkat.scala.entity.EmployeeKey other) {
    return new com.venkat.scala.entity.EmployeeKey.Builder(other);
  }

  /**
   * RecordBuilder for EmployeeKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeKey>
    implements org.apache.avro.data.RecordBuilder<EmployeeKey> {

    /** Source which uniquely identifies employee Id */
    private java.lang.CharSequence empId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.venkat.scala.entity.EmployeeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.empId)) {
        this.empId = data().deepCopy(fields()[0].schema(), other.empId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.venkat.scala.entity.EmployeeKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.empId)) {
        this.empId = data().deepCopy(fields()[0].schema(), other.empId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'empId' field.
      * Source which uniquely identifies employee Id
      * @return The value.
      */
    public java.lang.CharSequence getEmpId() {
      return empId;
    }

    /**
      * Sets the value of the 'empId' field.
      * Source which uniquely identifies employee Id
      * @param value The value of 'empId'.
      * @return This builder.
      */
    public com.venkat.scala.entity.EmployeeKey.Builder setEmpId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.empId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'empId' field has been set.
      * Source which uniquely identifies employee Id
      * @return True if the 'empId' field has been set, false otherwise.
      */
    public boolean hasEmpId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'empId' field.
      * Source which uniquely identifies employee Id
      * @return This builder.
      */
    public com.venkat.scala.entity.EmployeeKey.Builder clearEmpId() {
      empId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public EmployeeKey build() {
      try {
        EmployeeKey record = new EmployeeKey();
        record.empId = fieldSetFlags()[0] ? this.empId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
